name: Extend signposting variables
on:
  workflow_dispatch:
jobs:
  override_variables:
    name: Override variables
    runs-on: ubuntu-22.04
    steps:
      - name: Generate redirect
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          url=$(gh api "repos/$GITHUB_REPOSITORY/pages" --jq '.html_url')
          echo $url